### ISSUE TITLE
Enhancement influxdb

### ISSUE THREAD

**Issue by aimdev** [DCSO/fever#30]
Request that output can be fed directly into an influxdb.
https://www.influxdata.com
Information can then be presented with Grafana.
https://grafana.com

Thanks
PS I have managed to get this working via telegraf 
Suricata-->Fever-->Telegraf-->InfluxDb-->Grafana, so I suppose my enhancement request is no longer a high priority, but it would be nice :)

**Comment by aimdev** [comment]
Hi Sascha

I just want to get the eve data from Suricata to influx/postgres and on to Grafana

I have it sort of working, but, when using the metrics via rabbitmq to telegraf,

suricata —> socket —> fever —> rabbitmq —> telegraf —> influxdb —> grafana

I get this message, repeated

2019-01-29T11:14:02Z E! [inputs.amqp_consumer]: Error in plugin: unable to parse out as JSON, invalid character 'e' in literal false (expecting 'a’)

in the telegraf log.

The socket setup works ok, ie suricata —> socket —> fever —> socket —> telegraf —> influxdb —> grafana

With postgres, 

suricata —> socket —> fever —> postgres fever connects ok but whatever I try, there are no records inserted. 

Is fever supposed to create the database objects in the postgres database?
If I manually create the objects by cutting and pasting the ddl in the source code, still no inserts.

No errors in the fever log file.

It seems the /etc/fever/fever.yaml file is ‘ignored’ and you must put the required command in /etc/default/fever file
ie

#FEVER_ARGS=-n 0 -T  --logfile /var/log/fever/fever.log --config /etc/fever/fever.yaml --db-database "events"  --db-enable --db-host "localhost:5432"  --db-maxtablesize 50 --db-password "sensor" --db-rotate 1h0m0s --db-user "sensor"  --verbose       
FEVER_ARGS=-n 0 -T  --logfile /var/log/fever/fever.log --config /etc/fever/fever.yaml --metrics-enable  --verbose

(only one at a time is used of course)

I built fever from git yesterday, the debian version is old.
I also built suricata to version 4.1 (debian version also old, v3)

All this is on debian stretch, and all software is the latest versions.

I suspect I am doing something stupid!!

Your comment about Suricata runtime stats is not an issue for me, I didnt even know that the pull request  existed until you mentioned it.

Thanks

**Comment by aimdev** [comment]
Hi

after looking at the closed entries on github using -c2 I have data in the database!!
Will now use postgresql as the datastore..

suricata—> socket —>  fever —>  postgresql —> grfana (hopefully)

**Comment by satta** [comment]
> Hi Sascha I just want to get the eve data from Suricata to influx/postgres and on to Grafana

I am curious: Suricata produces highly structured EVE JSON, how would that fit into a time series database like InfluxDB and what would you be plotting in Grafana? Just the counts of events per time and event type? We only ever used it to store numeric values over time.

> With postgres, suricata —> socket —> fever —> postgres fever connects ok but whatever I try, there are no records inserted. Is fever supposed to create the database objects in the postgres database?

Yes. FEVER will create tables in the given database's public schema, one for each hour, fill them with events, and then run delayed indexing once a table is rotated away. 
You only need to make sure that the specified user (``) can create tables there. What does Postgres's log say?

> If I manually create the objects by cutting and pasting the ddl in the source code, still no inserts. 

There is no need to run anything directly, the documentation here just states the DDL for informational purposes.

> It seems the `/etc/fever/fever.yaml` file is ‘ignored’ and you must put the required command in `/etc/default/fever` file

Or just use `/root/.fever.yaml`. Alternatively you can just state `--config /etc/fever/fever.yaml` into the `/etc/default/fever.yaml`.

> I built fever from git yesterday, the debian version is old.

Yes, there is a certain amount of time that Debian packages need to transition from unstable to testing, and from there to backports. There will be a delay between a release here and the package hitting stretch-backports. Also, we currently need to address some test issues on some of the less popular Debian architectures, so please bear with us :)

**Comment by aimdev** [comment]
Hi
I am trying to design an alternative to SELKS, which is very resource heavy.
TIKS (Telegraf Influx etc) + grafana has in my experience a lower resource requirement, and is  easier to design.
All the monitoring here (snmp for the network, python for weather and gps) has been easy to implement, and is based on these components.
I came across fever and decided to investigate it  as an alternative means of retrieving Suricata data.
I have managed to get a pie chart displaying  protocol usage using the SFTIG nethod .
If it is not suitable I will create a bespoke python based  solution.

I have data from fever in the postgres database, and my next step would be to try to the function to provide data directly to grafana. 

re Or just use /root/.fever.yaml. 
Alternatively you can just state --config /etc/fever/fever.yaml into the /etc/default/fever.yaml.
I will try this.

Thanks

**Comment by satta** [comment]
OK, I see. However, I am not sure what data (apart from runtime metrics, see https://suricon.net/wp-content/uploads/2019/01/SuriCon2018_Steinbiss__Haist.pdf) you would like to see in InfluxDB/Grafana. For us FEVER was always meant as a tool to  gather and forward structured data such as actual EVE alerts including all metadata and other aggregated metadata (e.g. passive DNS observations), none of which I would consider to be a good fit for InfluxDB, which is optimized for numeric time series data.
If you want metrics like protocol histograms, events/second counts, etc. you can just use FEVER's metrics output which creates just that kind of data without any need to look at the EVE content. However, the metrics output only supports RabbitMQ for now.

Should we retitle this issue to "Support direct metrics input into InfluxDB" then or can this issue be closed?

**Comment by aimdev** [comment]
Hi

I have built a python program to read eve and insert  the data directly into postgresql and influxdb.

Thanks
