### ISSUE TITLE
Add reverse dns lookup functionality

### ISSUE THREAD

**Issue by rhaist** [DCSO/fever#35]
We want fever to use the sensor system resolver to make DNS lookups for specified Suricata event IP addresses (src & dst). This would preserve host name information at the time of the alert in the JSON itself and is especially helpful in networks with low DHCP lease times.

**Comment by satta** [comment]
That should be fairly straightforward to do, as long as the sensor can query the same DNS server as the monitored network. Do you have some system for specifying the relevant IPs in mind?

**Comment by satta** [comment]
@rhaist  Would it be sufficient to only do this for forwarded events (e.g. alerts)? Doing this step as late as possible in the reporting pipeline will make it easier to handle non-Suricata alerts (e.g. BLF or IP blacklist) and also help to keep the number of unnecessary requests low.

**Comment by satta** [comment]
Touched by https://github.com/DCSO/fever/commit/75816b730992ae1d69fd73557864fdf01124f0f2 -- please keep in mind though that this has the potential to cause infinite alerting loops if the sensor's reverse lookups are seen by itself.

**Comment by rhaist** [comment]
I understand. Should we make this lookup only for RFC1918 addresses?
Or do we cache the answer and reduce the occurrence of recursive alerting.
Or do we only make the lookup on non-dns alert events.

**Comment by satta** [comment]
> I understand. Should we make this lookup only for RFC1918 addresses?

Yep, makes sense and we should do that for now.

> Or do we cache the answer and reduce the occurrence of recursive alerting.

This is already implemented (using https://github.com/patrickmn/go-cache) in the commit mentioned above. I will add a separate switch to make the cache expiry duration configurable.

> Or do we only make the lookup on non-dns alert events.

Even if we do that, we can't know for sure that there is no DNS rule or BLF entry in place for the domain returned in the rDNS answer, so I am not sure that would help a lot.

**Comment by satta** [comment]
Closed via #36
