### ISSUE TITLE
Match against User-Agent in Bloom filter

### ISSUE THREAD

**Issue by King-Konsto** [DCSO/fever#37]
It would be great to match against known bad user-agents with the bloomfilter. I see to possibilities here:
1. Include bad user-agents in default bloomfilter and match against the http_user_agent field in HTTP eve output.
2. Include bad user-agents in a sort of blacklist and match against the http_user_agent field in HTTP eve output.

**Comment by satta** [comment]
I think 1. makes most sense here. User-Agents are an indicator type like any other, and may well be used in the default filter. Good idea! We need to keep in mind that only exact matches are supported though!

How many user agents do you typically expect?

**Comment by King-Konsto** [comment]
Close and handle with #38.
