### ISSUE TITLE
Match against TLS fingerprint in Bloom filter

### ISSUE THREAD

**Issue by klingerko** [DCSO/fever#38]
It would be great to match against known bad TLS certificate fingerprints and/or serial numbers with a bloomfilter. I see to possibilities here:
1. Include bad fingerprints/serial numbers in default bloomfilter and match against the belonging fields in tls eve output.
2. Include bad fingerpints/serial numbers in a sort of blacklist and match against the fingerprint/serial number feld in tls eve output.

**Comment by satta** [comment]
Like #37, this is fairly easy to do. We should do both in one go.

**Comment by King-Konsto** [comment]
Sounds great. I will count the current numbers of user-agents, and certificates to get an idea how much new indicators will be added to the bloomfilter.

**Comment by 0mbi** [comment]
I'll take that one.

**Comment by satta** [comment]
Closed via #76.
