### ISSUE TITLE
Make sure that FEVER retains all EVE-JSON fields

### ISSUE THREAD

**Issue by satta** [DCSO/fever#54]
FEVER needs to unmarshal/marshal EVE-JSON at least once while processing it. The rather dated  schema used in the code currently does not know about SMB, SIP, RDP, etc. and hence drops the associated metadata during the re-marshaling step.

We need to either update the schema to be up-to-date with the current Suricata 5.0.3 field set, or alternatively find a more dynamic way of accessing data.

This is easily 'fixable' by just passing through the JSON sub-objects as `interface{}`, but that does not allow FEVER to do checked access. It is only sufficient as long as we do not have a FEVER processor that needs the data in there.

**Comment by Rosemarymike** [comment]
The herbal medication Robinson Buckler mailed to me along with the prescriptions cured me from herpes and i am Negative For More Info on how to get cured Contact Robinson Buckler now on EMAIL ……………. Robinsonbuckler (@) yahoo. com_______________________________Thank you 🙏🙏🙏

**Comment by satta** [comment]
Closed via #55
