### ISSUE TITLE
Enable live update of Bloom filter

### ISSUE THREAD

**Issue by satta** [DCSO/fever#85]
It would be useful to be able to add new items to the currently running Bloom filter. A way of doing this would be to add a new `fever bloom` subcommand, which would allow to do things like:

- `fever bloom add foo.bar` to add a new indicator
- `fever bloom show` to display information about the state of the currently active Bloom filter
- `fever bloom reload` to reload the currently configured filter from disk
- ~~`fever bloom sync`~~ `fever bloom save` to sync the current memory state to disk

This subcommand could for example communicate with the FEVER process via a control socket.

**Comment by mavam** [comment]
I find `sync` a bit abstract. Maybe just use `save` and `load`, as they are nice duals to each other?

**Comment by satta** [comment]
Agreed. `bloom reload` and `bloom save` it is. I'd prefer to call it `reload` instead of `load` to stress that we only handle the preconfigured Bloom filter path.

**Comment by mavam** [comment]
> I'd prefer to call it `reload` instead of `load` to stress that we only handle the preconfigured Bloom filter path.

I have no strong opinion on this one. But you could also argue that this restriction may be weakened in the future.
